# siriusxm_script_example.yaml
# Example automation using the reusable SiriusXM playback script

automation:
  - id: siriusxm_script_turbo
    alias: Play Turbo via Script
    description: Plays Turbo using the reusable script when toggled.
    trigger:
      - platform: state
        entity_id: input_boolean.turbo
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.play_siriusxm_station
        data:
          station: "turbo"
          media_player: "media_player.alexa_device"
    mode: single
